// server.js
import express from "express";
import fs from "fs";
import path from "path";

const app = express();
const PORT = 5000;

// Path to the JSON file generated by your PDF extractor
const DATA_FILE = path.join(process.cwd(), "data", "questions.json");

// Middleware to parse JSON requests (if needed)
app.use(express.json());

// GET /api/questions?subject=biology&page=1&limit=20
app.get("/api/questions", (req, res) => {
  const { subject, page = 1, limit = 20 } = req.query;

  if (!fs.existsSync(DATA_FILE)) {
    return res.status(500).json({ error: "Questions data not found" });
  }

  const raw = fs.readFileSync(DATA_FILE, "utf-8");
  const allData = JSON.parse(raw);

  // Filter by subject if specified
  let filtered = allData;
  if (subject) {
    filtered = allData.filter(s => s.subject.toLowerCase() === subject.toLowerCase());
  }

  // Pagination
  const pageNum = parseInt(page);
  const limitNum = parseInt(limit);

  const paginated = filtered.map(s => {
    const start = (pageNum - 1) * limitNum;
    const end = start + limitNum;
    return {
      subject: s.subject,
      questions: s.questions.slice(start, end),
      totalQuestions: s.questions.length,
    };
  });

  res.json(paginated);
});

// GET all subjects
app.get("/api/subjects", (req, res) => {
  if (!fs.existsSync(DATA_FILE)) {
    return res.status(500).json({ error: "Questions data not found" });
  }

  const raw = fs.readFileSync(DATA_FILE, "utf-8");
  const allData = JSON.parse(raw);

  const subjects = allData.map(s => s.subject);
  res.json(subjects);
});

// Start server
app.listen(PORT, () => {
  console.log(`🚀 Server running on http://localhost:${PORT}`);
});